### ISSUE TITLE
add css files to your .gitignore

### ISSUE THREAD

**Issue by turchak** [Limonades/react.hw5#2]
At this point you might want to remove all CSS files from the source control, and add src/**/*.css to your .gitignore file. It is generally a `good practice` to keep the build products outside of the source control.

You can read about it here [Link](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)

**Comment by Limonades** [comment]
done

**Comment by turchak** [comment]
For a better experience, you have to delete all CSS files and add them to .gitignore file and don't add sass files to .gitignore.

**Comment by Limonades** [comment]
done
